---
name:         XML-Traverse-ParseTree
version:      0.03
version_from: lib/XML/Traverse/ParseTree.pm
author:
  - 'Martin Busik E<lt>martin.busik@busik.deE<gt>'
abstract: iterators and getters for xml access
license: perl
installdirs:  site
requires:
    perl:                          5.6.0
    Test::More:                    0.24
    XML::Parser:                   2.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
provides:
  XML::Traverse::ParseTree:
    file: lib/XML/Traverse/ParseTree
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
